Update test_and_render.yaml

diff --git a/.github/workflows/test_and_render.yaml b/.github/workflows/test_and_render.yaml
--- a/.github/workflows/test_and_render.yaml
+++ b/.github/workflows/test_and_render.yaml
@@ -26,26 +26,26 @@ jobs:
 
       - name: Check Disk Space (Before Cleanup)
         run: df -h
-#      - name: Cleanup Docker Space
-#        run: docker system prune -a --volumes -f
-#      - name: Clear BuildKit Cache
-#        run: rm -rf /var/lib/buildkit/*
-#      - name: Free disk space
-#        run: |
-#          # Disable swap (if it exists)
-#          sudo swapoff -a || true
-#          # Remove swapfile (if it exists)
-#          [ -f /swapfile ] && sudo rm -f /swapfile || true
-#          # Clean apt cache
-#          sudo apt clean
-#          # Remove Docker images, only if they exist
-#          docker images -q | xargs -r docker rmi || true  # 'xargs -r' will skip if no images are found
-#          # Clean up all unused Docker resources (images, containers, volumes)
-#          docker system prune -a --volumes -f || true
-#          # Show disk space after cleanup
-#          df -h
-#      - name: Check Disk Space (After Cleanup)
-#        run: df -h
+      - name: Cleanup Docker Space
+        run: docker system prune -a --volumes -f
+      - name: Clear BuildKit Cache
+        run: rm -rf /var/lib/buildkit/*
+      - name: Free disk space
+        run: |
+          # Disable swap (if it exists)
+          sudo swapoff -a || true
+          # Remove swapfile (if it exists)
+          [ -f /swapfile ] && sudo rm -f /swapfile || true
+          # Clean apt cache
+          sudo apt clean
+          # Remove Docker images, only if they exist
+          docker images -q | xargs -r docker rmi || true  # 'xargs -r' will skip if no images are found
+          # Clean up all unused Docker resources (images, containers, volumes)
+          docker system prune -a --volumes -f || true
+          # Show disk space after cleanup
+          df -h
+      - name: Check Disk Space (After Cleanup)
+        run: df -h
 
       # Step 3: Pull the Docker image from Docker Hub
       - name: Pull Docker image
